#include "rpyl_transpile.h"

#include "rpyl_config.h"
#include "rpyl_port.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static void c_escape_and_write(FILE* f, const char* s) {
    const unsigned char* p;
    unsigned char c;
    if (!f) return;
    if (!s) s = "";

    fputc('"', f);
    p = (const unsigned char*)s;
    while (*p) {
        c = *p++;
        if (c == '\\') {
            fputs("\\\\", f);
        } else if (c == '"') {
            fputs("\\\"", f);
        } else if (c == '\n') {
            fputs("\\n", f);
        } else if (c == '\r') {
            fputs("\\r", f);
        } else if (c == '\t') {
            fputs("\\t", f);
        } else if (c < 32 || c > 126) {
            /* hex escape */
            static const char hex[] = "0123456789ABCDEF";
            fputs("\\x", f);
            fputc(hex[(c >> 4) & 0xF], f);
            fputc(hex[c & 0xF], f);
        } else {
            fputc((int)c, f);
        }
    }
    fputc('"', f);
}

static void safe_ident(char* out, size_t out_sz, const char* in) {
    size_t i;
    size_t j;
    if (!out || out_sz == 0) return;

    if (!in || !in[0]) {
        rpyl_strcpy_trunc(out, out_sz, "rpyl_program");
        return;
    }

    /* Build a conservative C identifier: [A-Za-z_][A-Za-z0-9_]* */
    j = 0;
    for (i = 0; in[i] && j + 1 < out_sz; i++) {
        char c;
        c = in[i];
        if (j == 0) {
            if ((c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z') || c == '_') {
                out[j++] = c;
            } else if (c >= '0' && c <= '9') {
                out[j++] = '_';
                out[j++] = c;
            } else {
                out[j++] = '_';
            }
            continue;
        }

        if ((c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') || c == '_') {
            out[j++] = c;
        } else {
            out[j++] = '_';
        }
    }
    out[j] = 0;

    if (out[0] == 0) {
        rpyl_strcpy_trunc(out, out_sz, "rpyl_program");
    }
}

int rpyl_transpile_bytecode_to_c(
    const RpylBytecode* bc,
    const char* out_c_path,
    const char* symbol_prefix
) {
    FILE* f;
    char pref[RPYL_TRANSPILE_MAX_PREFIX];
    size_t i;
    size_t sc;
    size_t cc;
    size_t lc;
    size_t dc;

    if (!bc || !out_c_path) return 0;

    safe_ident(pref, sizeof(pref), symbol_prefix);

    sc = bc->string_count;
    cc = bc->code_count;
    lc = bc->label_count;
    dc = bc->define_count;

    /* C89 doesn't allow zero-length arrays. */
    if (sc == 0) sc = 1;
    if (cc == 0) cc = 1;
    if (lc == 0) lc = 1;
    if (dc == 0) dc = 1;

    f = fopen(out_c_path, "wb");
    if (!f) return 0;

    fprintf(f, "/* Auto-generated by rpyl_transpile_bytecode_to_c (C89) */\n");
    fprintf(f, "#include \"rpyl_bytecode.h\"\n");
    fprintf(f, "#include <string.h>\n\n");

    /* strings */
    fprintf(f, "static char* %s_strings[%lu] = {\n", pref, (unsigned long)sc);
    if (bc->string_count == 0) {
        fprintf(f, "    \"\"\n");
    }
    for (i = 0; i < bc->string_count; i++) {
        fprintf(f, "    ");
        c_escape_and_write(f, (bc->strings && bc->strings[i]) ? bc->strings[i] : "");
        if (i + 1 < bc->string_count) fprintf(f, ",");
        fprintf(f, "\n");
    }
    fprintf(f, "};\n\n");

    /* code */
    fprintf(f, "static rpyl_u32 %s_code[%lu] = {\n", pref, (unsigned long)cc);
    if (bc->code_count == 0) {
        fprintf(f, "    0\n");
    }
    for (i = 0; i < bc->code_count; i++) {
        fprintf(f, "    %lu", (unsigned long)bc->code[i]);
        if (i + 1 < bc->code_count) fprintf(f, ",");
        fprintf(f, "\n");
    }
    fprintf(f, "};\n\n");

    /* labels */
    fprintf(f, "static RpylBcLabel %s_labels[%lu] = {\n", pref, (unsigned long)lc);
    if (bc->label_count == 0) {
        fprintf(f, "    { 0, 0, 0 }\n");
    }
    for (i = 0; i < bc->label_count; i++) {
        fprintf(f, "    { %lu, %lu, %lu }", (unsigned long)bc->labels[i].name_sid, (unsigned long)bc->labels[i].ip, (unsigned long)bc->labels[i].end_ip);
        if (i + 1 < bc->label_count) fprintf(f, ",");
        fprintf(f, "\n");
    }
    fprintf(f, "};\n\n");

    /* defines */
    fprintf(f, "static RpylBcDefine %s_defines[%lu] = {\n", pref, (unsigned long)dc);
    if (bc->define_count == 0) {
        fprintf(f, "    { 0, 0 }\n");
    }
    for (i = 0; i < bc->define_count; i++) {
        fprintf(f, "    { %lu, %lu }", (unsigned long)bc->defines[i].name_sid, (unsigned long)bc->defines[i].value_sid);
        if (i + 1 < bc->define_count) fprintf(f, ",");
        fprintf(f, "\n");
    }
    fprintf(f, "};\n\n");

    fprintf(f, "static RpylBytecode %s_bc;\n", pref);
    fprintf(f, "static int %s_bc_inited = 0;\n\n", pref);

    fprintf(f, "const RpylBytecode* %s_get_bytecode(void) {\n", pref);
    fprintf(f, "    if (!%s_bc_inited) {\n", pref);
    fprintf(f, "        memset(&%s_bc, 0, sizeof(%s_bc));\n", pref, pref);
    fprintf(f, "        %s_bc.version = (rpyl_u32)RPYL_BC_VERSION;\n", pref);

    fprintf(f, "        %s_bc.strings = %s_strings;\n", pref, pref);
    fprintf(f, "        %s_bc.string_count = (size_t)%lu;\n", pref, (unsigned long)bc->string_count);
    fprintf(f, "        %s_bc.string_cap = (size_t)%lu;\n", pref, (unsigned long)sc);

    fprintf(f, "        %s_bc.code = %s_code;\n", pref, pref);
    fprintf(f, "        %s_bc.code_count = (size_t)%lu;\n", pref, (unsigned long)bc->code_count);
    fprintf(f, "        %s_bc.code_cap = (size_t)%lu;\n", pref, (unsigned long)cc);

    fprintf(f, "        %s_bc.labels = %s_labels;\n", pref, pref);
    fprintf(f, "        %s_bc.label_count = (size_t)%lu;\n", pref, (unsigned long)bc->label_count);
    fprintf(f, "        %s_bc.label_cap = (size_t)%lu;\n", pref, (unsigned long)lc);

    fprintf(f, "        %s_bc.defines = %s_defines;\n", pref, pref);
    fprintf(f, "        %s_bc.define_count = (size_t)%lu;\n", pref, (unsigned long)bc->define_count);
    fprintf(f, "        %s_bc.define_cap = (size_t)%lu;\n", pref, (unsigned long)dc);

    fprintf(f, "        %s_bc.next_once_id = 1;\n", pref);
    fprintf(f, "        %s_bc_inited = 1;\n", pref);
    fprintf(f, "    }\n");
    fprintf(f, "    return &%s_bc;\n", pref);
    fprintf(f, "}\n");

    fclose(f);
    return 1;
}
